"""filepath列などの実db乖離を追いつかせる

Revision ID: 13361519c72b
Revises: c8f795cc342a
Create Date: 2026-09-19 23:22:44.786049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13361519c72b'
down_revision: Union[str, Sequence[str], None] = 'c8f795cc342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('character_drive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('kind', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('kind', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('character_drive', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
