"""abolish_plot_tables

Revision ID: 5c15aeb8dd47
Revises: 5d316428a6aa
Create Date: 2026-09-23 19:26:08.580360

`character_plot` の本文は人物の `text` へ、`plot` の本文は作品(`story`)の `text` へ、
どちらも `# plot` の節として畳んでからテーブルを落とす。

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from DEM.db.stamp import Stamp


# revision identifiers, used by Alembic.
revision: str = '5c15aeb8dd47'
down_revision: Union[str, Sequence[str], None] = '5d316428a6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PLOT_HEADING = "# plot"


def _year(value) -> str:
    stamp = Stamp.from_int(value) if value is not None else None
    return str(stamp.year) if stamp else ""


def _section_label(start, end, filename: str | None) -> str:
    start_label, end_label = _year(start), _year(end)
    span = f"{start_label}〜{end_label}" if (start_label or end_label) else ""
    return " ".join(part for part in (span, filename or "") if part)


def _plot_section(rows) -> str:
    """`(start, end, filename, text)` の並びを `# plot` の節一つに畳む。"""
    blocks = []
    for start, end, filename, text in rows:
        body = (text or "").strip()
        label = _section_label(start, end, filename)
        if label:
            blocks.append(f"## {label}\n{body}" if body else f"## {label}")
        elif body:
            blocks.append(body)
    if not blocks:
        return ""
    return f"{PLOT_HEADING}\n\n" + "\n\n".join(blocks)


def _append_section(text: str | None, section: str) -> str:
    head = (text or "").rstrip()
    return f"{head}\n\n{section}" if head else section


def _world_id(conn, location_id):
    """`location_id` からたどれる一番上の場所。作品の `world_id` に置く。"""
    current = location_id
    while current is not None:
        parent = conn.execute(
            sa.text("SELECT parent_id FROM location WHERE id = :id"), {"id": current}
        ).scalar()
        if parent is None:
            return current
        current = parent
    return None


def _fold_character_plots(conn) -> None:
    rows = conn.execute(sa.text(
        "SELECT character_id, start, end, filename, text FROM character_plot "
        "WHERE character_id IS NOT NULL ORDER BY character_id, start, id"
    )).fetchall()
    by_character: dict[int, list] = {}
    for character_id, start, end, filename, text in rows:
        by_character.setdefault(character_id, []).append((start, end, filename, text))

    for character_id, plots in by_character.items():
        section = _plot_section(plots)
        if not section:
            continue
        current = conn.execute(
            sa.text("SELECT text FROM character WHERE id = :id"), {"id": character_id}
        ).scalar_one_or_none()
        conn.execute(
            sa.text("UPDATE character SET text = :text WHERE id = :id"),
            {"text": _append_section(current, section), "id": character_id})


def _fold_plots(conn) -> None:
    stories = {
        name: story_id for story_id, name
        in conn.execute(sa.text("SELECT id, name FROM story")).fetchall()
    }
    rows = conn.execute(sa.text(
        "SELECT id, location_id, start, end, directory_path, filename, text FROM plot ORDER BY id"
    )).fetchall()

    for plot_id, location_id, start, end, directory_path, filename, text in rows:
        section = _plot_section([(start, end, filename, text)])
        if not section:
            continue
        story_id = stories.get(filename)
        if story_id is not None:
            current = conn.execute(
                sa.text("SELECT text FROM story WHERE id = :id"), {"id": story_id}
            ).scalar_one_or_none()
            conn.execute(
                sa.text("UPDATE story SET text = :text WHERE id = :id"),
                {"text": _append_section(current, section), "id": story_id})
            continue

        conn.execute(sa.text(
            "INSERT INTO story (name, world_id, place_id, narration, state, start, end, "
            "text, directory_path, filename) "
            "VALUES (:name, :world_id, :place_id, '', '構想中', :start, :end, "
            ":text, :directory_path, NULL)"
        ), {"name": filename or f"plot {plot_id}",
            "world_id": _world_id(conn, location_id),
            "place_id": location_id,
            "start": start, "end": end,
            "text": section,
            "directory_path": directory_path})


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    _fold_character_plots(conn)
    _fold_plots(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_plot_character_id'))

    op.drop_table('character_plot')
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_location_id'))

    op.drop_table('plot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 畳んだ `# plot` の節は戻さない。空のテーブルだけ作り直す。
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot',
    sa.Column('start', sa.BIGINT(), nullable=True),
    sa.Column('end', sa.BIGINT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('directory_path', sa.VARCHAR(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_location_id'), ['location_id'], unique=False)

    op.create_table('character_plot',
    sa.Column('start', sa.BIGINT(), nullable=True),
    sa.Column('end', sa.BIGINT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('directory_path', sa.VARCHAR(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_plot_character_id'), ['character_id'], unique=False)

    # ### end Alembic commands ###
