"""id列をInteger主キーに直しautoincrementを効かせる

Revision ID: afb1401a020d
Revises: 6b8a0db2cf29
Create Date: 2026-09-19 20:21:46.588638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb1401a020d'
down_revision: Union[str, Sequence[str], None] = '6b8a0db2cf29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_character_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('character_drive', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_character_drive_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('character_place', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('character_skill', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_episode_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_event_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('kind', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_kind_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_location_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_object_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('object_place', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_skill_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_story_filepath'))
        batch_op.drop_column('filepath')

    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_term_filepath'))
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_term_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_story_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_skill_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('object_place', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_object_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_location_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('kind', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_kind_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_event_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_episode_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('character_skill', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('character_place', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('character_drive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_character_drive_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_character_filepath'), ['filepath'], unique=1)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
