"""plot テーブルを追加

Revision ID: fe6446b916d0
Revises: b7edc9a5acc3
Create Date: 2026-09-20 19:47:23.440524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6446b916d0'
down_revision: Union[str, Sequence[str], None] = 'b7edc9a5acc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='この筋書きが掛かる場所。空なら場所を問わない'),
    sa.Column('event', sa.String(), nullable=False, comment='この場所の出来事生成に指示したい筋書き'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plot_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_place_id'))
        batch_op.create_index(batch_op.f('ix_event_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_location_id'))
        batch_op.create_index(batch_op.f('ix_event_place_id'), ['location_id'], unique=False)

    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plot_location_id'))

    op.drop_table('plot')
    # ### end Alembic commands ###
