"""location に広さ・環境を追加し location_resource を作成

Revision ID: 4d305c506a4c
Revises: bf21fb9144ac
Create Date: 2026-09-20 10:41:05.832460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import DEM.db.schema


# revision identifiers, used by Alembic.
revision: str = '4d305c506a4c'
down_revision: Union[str, Sequence[str], None] = 'bf21fb9144ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_resource',
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.Column('kind', sa.String(), nullable=False, comment='種別'),
                    sa.Column('quantity', sa.Integer(), nullable=False, comment='総量。start 時点の量'),
                    sa.Column('unit', sa.String(), nullable=False, comment='単位'),
                    sa.Column('start', DEM.db.schema.StampType(), nullable=False, comment='この量を数え始める時刻。総量ぶんある'),
                    sa.Column('end', DEM.db.schema.StampType(), nullable=False, comment='尽きる時刻。0になる'),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('filepath', sa.String(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('location_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_resource_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.DECIMAL(), nullable=True, comment='広さ。単位は決めていないが、親と子で揃える。子の広さは親未満、兄弟(同じ parent_id)を足しても親を超えない'))
        batch_op.add_column(sa.Column('environment', sa.String(), nullable=True, comment='環境'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('environment')
        batch_op.drop_column('area')

    with op.batch_alter_table('location_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_resource_location_id'))

    op.drop_table('location_resource')
    # ### end Alembic commands ###
