"""locationにランダム生成フラグを追加

Revision ID: 8adfa8e49814
Revises: 7e559b4d98d3
Create Date: 2026-09-20 14:57:04.553955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adfa8e49814'
down_revision: Union[str, Sequence[str], None] = '7e559b4d98d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'random_character_source', sa.Boolean(), nullable=False,
            server_default=sa.false(),
            comment='オンなら、この場所にまだ人物が一人も居ないとき、月初の判定でまとめて1〜4人を生成する対象にする(DEM/local_ai/time_keeper/random_character_generator.py の seed_initial_characters)。長期間、場所ごとの人物が増えない問題への対処'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('random_character_source')

    # ### end Alembic commands ###
