"""plot に text filepath start end を持たせる

Revision ID: 88bc0ba4177e
Revises: fe6446b916d0
Create Date: 2026-09-20 20:02:18.857528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import DEM.db.schema

# revision identifiers, used by Alembic.
revision: str = '88bc0ba4177e'
down_revision: Union[str, Sequence[str], None] = 'fe6446b916d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', DEM.db.schema.StampType(), nullable=True))
        batch_op.add_column(sa.Column('end', DEM.db.schema.StampType(), nullable=True))
        batch_op.add_column(sa.Column('text', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.String(), nullable=True))
        batch_op.drop_column('event')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('filepath')
        batch_op.drop_column('text')
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    # ### end Alembic commands ###
