"""idea alias_of_idea_id

Revision ID: 746563537df1
Revises: 51a2863be722
Create Date: 2026-09-26 11:58:23.046400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746563537df1'
down_revision: Union[str, Sequence[str], None] = '51a2863be722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias_of_idea_id', sa.Integer(), nullable=True, comment='作中での呼び名であるときの、本質のアイデア。呼び名は location_id・start・end の場所と時代で使い、空の列はどこでも・いつでも使う。当てはまる呼び名が無ければ本質の name をそのまま使う'))
        batch_op.create_index(batch_op.f('ix_idea_alias_of_idea_id'), ['alias_of_idea_id'], unique=False)
        batch_op.create_foreign_key('fk_idea_alias_of_idea_id_idea', 'idea', ['alias_of_idea_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_constraint('fk_idea_alias_of_idea_id_idea', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_idea_alias_of_idea_id'))
        batch_op.drop_column('alias_of_idea_id')

    # ### end Alembic commands ###
