"""話数をやめて話を start で並べる

Revision ID: 76647cacb176
Revises: 746563537df1
Create Date: 2026-09-26 12:43:41.854468

"""
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

EPISODE_REF = re.compile(r"第(\d+)(?:〜(\d+))?話")
HOUR = 10000  # start は yyyymmddhhmmss の整数


# revision identifiers, used by Alembic.
revision: str = '76647cacb176'
down_revision: Union[str, Sequence[str], None] = '746563537df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _spread_same_starts(conn) -> None:
    """番号が消えると同じ start の話の並びが決まらないので、番号順に一時間ずつずらす"""
    rows = conn.execute(sa.text(
        "select id, story_id, start from episode where start is not null order by story_id, start, number, id")).all()
    seen: dict[tuple[int, int], int] = {}
    for episode_id, story_id, start in rows:
        offset = seen.get((story_id, start), 0)
        seen[(story_id, start)] = offset + 1
        if offset:
            if (start // HOUR) % 100 + offset >= 24:
                raise RuntimeError(f"episode id={episode_id}: 同じ start の話が多すぎて一日に収まらない")
            conn.execute(sa.text("update episode set start = :start where id = :id"),
                         {"start": start + offset * HOUR, "id": episode_id})


def _refs_to_titles(conn) -> None:
    """本文・種・作品の `第N話` を、その作品の話の題 `『題』の話` に置き換える"""
    for (story_id,) in conn.execute(sa.text("select distinct story_id from episode")).all():
        titles = {number: title for number, title in conn.execute(sa.text(
            "select number, title from episode where story_id = :s and number is not null"), {"s": story_id})}

        def repl(m: re.Match) -> str:
            first, last = int(m.group(1)), m.group(2)
            if first not in titles or (last is not None and int(last) not in titles):
                return m.group(0)
            if last is None:
                return f"『{titles[first]}』の話"
            return f"『{titles[first]}』〜『{titles[int(last)]}』の話"

        for episode_id, key, text in conn.execute(sa.text(
                "select id, key, text from episode where story_id = :s"), {"s": story_id}).all():
            conn.execute(sa.text("update episode set key = :k, text = :t where id = :id"),
                         {"k": EPISODE_REF.sub(repl, key or ""), "t": EPISODE_REF.sub(repl, text or ""),
                          "id": episode_id})
        story_text = conn.execute(sa.text("select text from story where id = :s"), {"s": story_id}).scalar()
        conn.execute(sa.text("update story set text = :t where id = :s"),
                     {"t": EPISODE_REF.sub(repl, story_text or ""), "s": story_id})


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    _spread_same_starts(conn)
    _refs_to_titles(conn)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
    # 番号は並び順から振り直す。『題』に置き換えた参照は戻さない
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "select id, story_id from episode order by story_id, start is null, start, id")).all()
    numbers: dict[int, int] = {}
    for episode_id, story_id in rows:
        numbers[story_id] = numbers.get(story_id, 0) + 1
        conn.execute(sa.text("update episode set number = :n where id = :id"),
                     {"n": numbers[story_id], "id": episode_id})
