"""人物のパラメータを期間ごとに持つ

Revision ID: 0f79bf0af917
Revises: 76647cacb176
Create Date: 2026-09-26 13:36:42.061011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f79bf0af917'
down_revision: Union[str, Sequence[str], None] = '76647cacb176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

PERSON_COLUMNS = ("sex", "height", "build", "first_person", "second_person", "third_person", "tone", "dialect")
PERSONALITY_COLUMNS = (
    "sincerity", "curiosity", "proactivity", "cooperativeness", "sociability",
    "emotional_expression", "self_esteem", "self_efficacy", "stress_resilience",
    "flexibility_of_values", "sensitivity", "imagination",
)
COLUMNS = PERSON_COLUMNS + PERSONALITY_COLUMNS


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='この値が効き始める時。空なら初めから'),
    sa.Column('end', sa.BigInteger(), nullable=True, comment='この値が効き終わる時(この時からは効かない)。空なら終わりまで'),
    sa.Column('sex', sa.String(), nullable=True, comment='性別'),
    sa.Column('height', sa.DECIMAL(), nullable=True, comment='背丈 cm'),
    sa.Column('build', sa.String(), nullable=True, comment='体格'),
    sa.Column('first_person', sa.String(), nullable=True, comment='一人称'),
    sa.Column('second_person', sa.String(), nullable=True, comment='二人称'),
    sa.Column('third_person', sa.String(), nullable=True, comment='三人称'),
    sa.Column('tone', sa.String(), nullable=True, comment='口調'),
    sa.Column('dialect', sa.String(), nullable=True, comment='方言。方言の種類か、標準語で話すならその癖(語尾・言い回し・訛り)'),
    sa.Column('sincerity', sa.String(), nullable=True, comment='誠実性'),
    sa.Column('curiosity', sa.String(), nullable=True, comment='好奇心'),
    sa.Column('proactivity', sa.String(), nullable=True, comment='行動力'),
    sa.Column('cooperativeness', sa.String(), nullable=True, comment='協調性'),
    sa.Column('sociability', sa.String(), nullable=True, comment='社交性'),
    sa.Column('emotional_expression', sa.String(), nullable=True, comment='感情表現'),
    sa.Column('self_esteem', sa.String(), nullable=True, comment='自己肯定感'),
    sa.Column('self_efficacy', sa.String(), nullable=True, comment='自己効力感'),
    sa.Column('stress_resilience', sa.String(), nullable=True, comment='ストレス耐性'),
    sa.Column('flexibility_of_values', sa.String(), nullable=True, comment='価値観の柔軟性'),
    sa.Column('sensitivity', sa.String(), nullable=True, comment='感受性'),
    sa.Column('imagination', sa.String(), nullable=True, comment='想像力'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_parameter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_parameter_character_id'), ['character_id'], unique=False)

    # ### end Alembic commands ###
    # いまの値は、期間を限らない一行として移す
    columns = ", ".join(COLUMNS)
    op.execute(
        f"insert into character_parameter (character_id, {columns}) "
        f"select id, {columns} from character order by id")

    with op.batch_alter_table('character', schema=None) as batch_op:
        for column in COLUMNS:
            batch_op.drop_column(column)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('character', schema=None) as batch_op:
        for column in PERSON_COLUMNS:
            batch_op.add_column(sa.Column(column, sa.DECIMAL() if column == "height" else sa.VARCHAR(), nullable=True))
        for column in PERSONALITY_COLUMNS:
            batch_op.add_column(sa.Column(column, sa.VARCHAR(), nullable=False, server_default="並"))

    # 期間を限らない行だけを戻す。期間を限った行は捨てる
    for column in PERSON_COLUMNS:
        op.execute(
            f"update character set {column} = (select p.{column} from character_parameter p "
            f"where p.character_id = character.id and p.start is null and p.\"end\" is null "
            f"and p.{column} is not null order by p.id desc limit 1)")
    for column in PERSONALITY_COLUMNS:
        op.execute(
            f"update character set {column} = coalesce((select p.{column} from character_parameter p "
            f"where p.character_id = character.id and p.start is null and p.\"end\" is null "
            f"and p.{column} is not null order by p.id desc limit 1), '並')")

    with op.batch_alter_table('character_parameter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_parameter_character_id'))

    op.drop_table('character_parameter')
