"""人物の名字を期間ごとに持つ

Revision ID: 1bdb6a716b4b
Revises: 0f79bf0af917
Create Date: 2026-09-26 16:30:51.509877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdb6a716b4b'
down_revision: Union[str, Sequence[str], None] = '0f79bf0af917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_name', sa.String(), nullable=True, comment='名字。結婚・養子・家の取り立てなどで変わる。名字を持たない身分なら空'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_parameter', schema=None) as batch_op:
        batch_op.drop_column('family_name')

    # ### end Alembic commands ###
