"""drop character read

Revision ID: e849a5b683f6
Revises: a3cb4c2069e0
Create Date: 2026-09-23 12:13:27.365984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e849a5b683f6'
down_revision: Union[str, Sequence[str], None] = 'a3cb4c2069e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
