"""add_character_sub_character_flag

Revision ID: 5d316428a6aa
Revises: e849a5b683f6
Create Date: 2026-09-23 13:19:29.542235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d316428a6aa'
down_revision: Union[str, Sequence[str], None] = 'e849a5b683f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_character', sa.Boolean(), nullable=False, server_default=sa.false(), comment='メインキャラクター以外のサブキャラクターか。出来事・筋書きのランダム生成は、この列が true の人物・対象だけを対象にする'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('sub_character')

    # ### end Alembic commands ###
