"""eventのkindを廃止しhiddenを追加

Revision ID: bc7493a69e2c
Revises: 8adfa8e49814
Create Date: 2026-09-21 10:27:16.646948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7493a69e2c'
down_revision: Union[str, Sequence[str], None] = '8adfa8e49814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'hidden', sa.Boolean(), nullable=False, server_default=sa.false(),
            comment='断面(ReadBrief)に出すか。伏せたい裏設定・伏線はこれを立てる'))
        batch_op.drop_column('kind')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'kind', sa.VARCHAR(), nullable=False, server_default=''))
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
