"""location_resourceを廃止する

Revision ID: 70fc942aa95b
Revises: 8b564f6f4bc3
Create Date: 2026-09-21 13:49:33.062023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fc942aa95b'
down_revision: Union[str, Sequence[str], None] = '8b564f6f4bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_resource_location_id'))

    op.drop_table('location_resource')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_resource',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('start', sa.BIGINT(), nullable=False),
    sa.Column('end', sa.BIGINT(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('directory_path', sa.VARCHAR(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_resource_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###
