"""character_plotを追加する

Revision ID: f5dec0a954e7
Revises: 70fc942aa95b
Create Date: 2026-09-21 14:16:27.171648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import DEM.db.schema

# revision identifiers, used by Alembic.
revision: str = 'f5dec0a954e7'
down_revision: Union[str, Sequence[str], None] = '70fc942aa95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_plot',
    sa.Column('start', DEM.db.schema.StampType(), nullable=True),
    sa.Column('end', DEM.db.schema.StampType(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False, comment='この筋書きが掛かる人物'),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('directory_path', sa.String(), nullable=True, comment='import,export時の配置先。worlds/{table}/ からの相対ディレクトリパス。空ならテーブル直下に置く'),
    sa.Column('filename', sa.String(), nullable=True, comment='import,export時のファイル名(id・拡張子を除いた部分)。空なら {id}.md。テーブルが持つ name 等の列とは別物'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_plot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_plot_character_id'), ['character_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_plot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_plot_character_id'))

    op.drop_table('character_plot')
    # ### end Alembic commands ###
