"""character_driveを廃止しcharacter_plotへ一本化

Revision ID: 82697cf669fa
Revises: 1c17cbc51fbd
Create Date: 2026-09-21 18:55:49.054214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82697cf669fa'
down_revision: Union[str, Sequence[str], None] = '1c17cbc51fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_drive')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_drive',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('start', sa.BIGINT(), nullable=True),
    sa.Column('end', sa.BIGINT(), nullable=True),
    sa.Column('directory_path', sa.VARCHAR(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
