"""objectを廃止しcharacterへ一本化、character.kindを追加

Revision ID: 4c3ab4cc7d2d
Revises: 82697cf669fa
Create Date: 2026-09-21 21:47:36.365101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3ab4cc7d2d'
down_revision: Union[str, Sequence[str], None] = '82697cf669fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # character の belong_id は object を参照しているので、object を落とす前に
    # character 側を作り直す(batch の反映で参照先の表が要る)。
    with op.batch_alter_table('character', schema=None) as batch_op:
        # 既存行(人物しか無い)を埋めるため server_default を付ける。モデル側は default のみ。
        batch_op.add_column(sa.Column('kind', sa.String(), nullable=False, server_default='人物', comment='種別。「人物」か、人物以外の対象(国・組織・商会・氏族・集団・物など)'))
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('build',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('first_person',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('second_person',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('third_person',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('tone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('belong_id')

    op.drop_table('object_place')
    with op.batch_alter_table('event_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_object_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_object_object_id'))

    op.drop_table('event_object')
    op.drop_table('object')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('read', sa.VARCHAR(), nullable=True),
    sa.Column('world_influence', sa.INTEGER(), nullable=False),
    sa.Column('start', sa.BIGINT(), nullable=True),
    sa.Column('end', sa.BIGINT(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('directory_path', sa.VARCHAR(), nullable=True),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_object',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('object_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_object_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_object_event_id'), ['event_id'], unique=False)

    op.create_table('object_place',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('object_id', sa.INTEGER(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=False),
    sa.Column('start', sa.BIGINT(), nullable=True),
    sa.Column('end', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('belong_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'object', ['belong_id'], ['id'])
        batch_op.alter_column('tone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('third_person',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('second_person',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('first_person',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('build',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('sex',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
