"""add location.active_random_generation

Revision ID: 1cbdb9136ca5
Revises: 4c3ab4cc7d2d
Create Date: 2026-09-21 23:21:34.283898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbdb9136ca5'
down_revision: Union[str, Sequence[str], None] = '4c3ab4cc7d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        # 既存行を埋めるため server_default を付ける。モデル側は default のみ。
        batch_op.add_column(sa.Column(
            'active_random_generation', sa.Boolean(), nullable=False,
            server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('active_random_generation')

    # ### end Alembic commands ###
