"""出来事と作品の要約テーブルを足す

Revision ID: 24327ee59e1c
Revises: 052069310f38
Create Date: 2026-09-24 06:17:12.570762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24327ee59e1c'
down_revision: Union[str, Sequence[str], None] = '052069310f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False, comment='要約した本文の sha256。本文と食い違ったら作り直す'),
    sa.Column('text', sa.String(), nullable=False, comment='要約'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_summary_event_id'), ['event_id'], unique=True)

    op.create_table('story_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False, comment='要約した本文の sha256。本文と食い違ったら作り直す'),
    sa.Column('summary', sa.String(), nullable=False, comment='概要'),
    sa.Column('style', sa.String(), nullable=False, comment='文体の覚え書き'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_summary_episode_id'), ['episode_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_story_summary_story_id'), ['story_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_summary_story_id'))
        batch_op.drop_index(batch_op.f('ix_story_summary_episode_id'))

    op.drop_table('story_summary')
    with op.batch_alter_table('event_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_summary_event_id'))

    op.drop_table('event_summary')
    # ### end Alembic commands ###
