"""出来事の種テーブルを足す

Revision ID: cd51e8d34592
Revises: 82c20d8db0c5
Create Date: 2026-09-24 07:50:00.977734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd51e8d34592'
down_revision: Union[str, Sequence[str], None] = '82c20d8db0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_seed_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False, comment='元の種類。story / episode / character'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='元のレコードの id'),
    sa.Column('source_hash', sa.String(), nullable=False, comment='種を抜き出した本文の sha256。本文と食い違ったら抜き出し直す'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id')
    )
    op.create_table('event_seed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_seed_source_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False, comment='種'),
    sa.ForeignKeyConstraint(['event_seed_source_id'], ['event_seed_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_seed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_seed_event_seed_source_id'), ['event_seed_source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_seed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_seed_event_seed_source_id'))

    op.drop_table('event_seed')
    op.drop_table('event_seed_source')
    # ### end Alembic commands ###
