"""出来事の種に棚卸し済みフラグを足す

Revision ID: 56c6bd7ffe26
Revises: f8eefc75dad5
Create Date: 2026-09-24 08:20:49.419516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c6bd7ffe26'
down_revision: Union[str, Sequence[str], None] = 'f8eefc75dad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_seed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consolidated', sa.Boolean(), nullable=False, server_default=sa.false(), comment='棚卸し(似た種をまとめる)を済ませたか。新しい種は false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_seed', schema=None) as batch_op:
        batch_op.drop_column('consolidated')

    # ### end Alembic commands ###
