"""add character dialect

Revision ID: 37f8b0a380e9
Revises: 0ca6fda25c60
Create Date: 2026-09-24 18:57:50.589499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f8b0a380e9'
down_revision: Union[str, Sequence[str], None] = '0ca6fda25c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dialect', sa.String(), nullable=True, comment='方言。方言の種類か、標準語で話すならその癖(語尾・言い回し・訛り)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('dialect')

    # ### end Alembic commands ###
